# Generated by Django 5.0.6 on 2024-05-27 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plate',
            fields=[
                ('plateID', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(7)])),
            ],
        ),
    ]
