# Generated by Django 4.2.13 on 2024-05-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placa', models.CharField(max_length=15, verbose_name='Placas')),
            ],
        ),
    ]
